project:
  type: website

website:
  title: "{{ cookiecutter.project_name }}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true

output-dir: ../docs
